CREATE TABLE TB_FORNECEDOR (
    CD_FORNECEDOR NUMBER(3) PRIMARY KEY,
    NM_FORNECEDOR VARCHAR2(70) NOT NULL,
    NM_CONTATO VARCHAR2(70) NOT NULL,
    DT_CADASTRO DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SQ_FORNECEDOR
    START WITH 1
    INCREMENT BY 1;



INSERT INTO tb_fornecedor (CD_FORNECEDOR, NM_FORNECEDOR, NM_CONTATO)
VALUES (SQ_FORNECEDOR.NEXTVAL, 'JOSÉ', 'MARIA');

INSERT INTO tb_fornecedor (CD_FORNECEDOR, NM_FORNECEDOR, NM_CONTATO, DT_CADASTRO)
VALUES (SQ_FORNECEDOR.NEXTVAL, 'JOSÉ', 'MARIA', '10/10/22');


SELECT * FROM tb_fornecedor;
















