CREATE TABLE TB_FUNCIONARIO (
    MATRICULA NUMBER(3) PRIMARY KEY,
    NOME VARCHAR2(60) NOT NULL,
    SALARIO NUMBER(10,2) NOT NULL
);

CREATE SEQUENCE SQ_FUNCIONARIO
    START WITH 1
    INCREMENT BY 1;


INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SALARIO) 
    VALUES (SQ_FUNCIONARIO.NEXTVAL, 'VINÍCIUS', 2500.00);

INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SALARIO) 
    VALUES (SQ_FUNCIONARIO.NEXTVAL, 'JOSÉ', 2000.00);

INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SALARIO) 
    VALUES (SQ_FUNCIONARIO.NEXTVAL, 'MARIA', 3000.00);
    
SELECT * FROM tb_funcionario;


CREATE OR REPLACE TRIGGER TG_UPDATE_FUNCIONARIO 
BEFORE UPDATE ON TB_FUNCIONARIO
FOR EACH ROW
BEGIN  
    IF (:NEW.SALARIO < :OLD.SALARIO) THEN
            RAISE_APPLICATION_ERROR(-20000, 'O SALÁRIO NOVO NÃO PODE SER MENOR QUE O ANTERIOR.');
        END IF;
END;

-- TESTE PARA UM UPDATE PERMITIDO 
UPDATE tb_funcionario 
SET salario = 4000
WHERE matricula = 2;

-- TESTE PARA UM UPDATE NÃO PERMITIDO 
UPDATE tb_funcionario 
SET salario = 1000
WHERE matricula = 3;

SELECT * FROM tb_funcionario;